port=53
listen-address=127.0.0.1,10.63.169.3
bind-interfaces
no-hosts
no-resolv
server=10.63.169.210
local=/teamcn.test/
host-record=app.teamcn.test,10.63.169.3
host-record=api.teamcn.test,10.63.169.72
local-ttl=60
log-queries
log-facility=-
